import { z } from "zod";

/**
 * Single source of truth for every shape that crosses a boundary:
 * browser -> API, API -> Gemini, Gemini -> API, API -> browser.
 *
 * "*ModelSchema" = what Gemini is asked to produce (structured output).
 * "*OutputSchema" = what the app renders; always carries the fixed disclaimer,
 * which is appended by our code, never trusted to the model.
 */

export const DISCLAIMER =
  "This is general legal information generated by AI, not legal advice. It may be incomplete or wrong. Consult a licensed attorney before making decisions about this document.";

export const QA_DISCLAIMER =
  "This answer is based solely on the document you uploaded. Consult a licensed attorney for legal advice.";

// ---------------------------------------------------------------------------
// Limits
// ---------------------------------------------------------------------------

export const LIMITS = {
  maxPages: 80,
  maxCharsPerDocument: 300_000,
  maxChunks: 260,
  maxQueryChars: 600,
  maxFileBytes: 8 * 1024 * 1024,
  embeddingDims: 768,
} as const;

// ---------------------------------------------------------------------------
// Reader preferences (accessibility: language and reading level)
// ---------------------------------------------------------------------------

export const LANGUAGES = {
  en: { label: "English", speech: "en-US" },
  hi: { label: "हिन्दी (Hindi)", speech: "hi-IN" },
  es: { label: "Español (Spanish)", speech: "es-ES" },
  fr: { label: "Français (French)", speech: "fr-FR" },
  pt: { label: "Português (Portuguese)", speech: "pt-BR" },
  de: { label: "Deutsch (German)", speech: "de-DE" },
  bn: { label: "বাংলা (Bengali)", speech: "bn-IN" },
  ta: { label: "தமிழ் (Tamil)", speech: "ta-IN" },
  zh: { label: "中文 (Chinese, Simplified)", speech: "zh-CN" },
} as const;
export const LanguageSchema = z.enum(["en", "hi", "es", "fr", "pt", "de", "bn", "ta", "zh"]);
export type Language = z.infer<typeof LanguageSchema>;

export const ReadingLevelSchema = z.enum(["simple", "standard", "detailed"]);
export type ReadingLevel = z.infer<typeof ReadingLevelSchema>;

export const PreferencesSchema = z.object({
  language: LanguageSchema.default("en"),
  readingLevel: ReadingLevelSchema.default("standard"),
});
export type Preferences = z.infer<typeof PreferencesSchema>;

// ---------------------------------------------------------------------------
// Documents
// ---------------------------------------------------------------------------

export const PageSchema = z.object({
  page: z.number().int().min(1),
  text: z.string().max(60_000),
});
export type Page = z.infer<typeof PageSchema>;

export const DocumentChunkSchema = z.object({
  id: z.string().min(1).max(40),
  page: z.number().int().min(1),
  endPage: z.number().int().min(1),
  section: z.string().max(200),
  text: z.string().min(1).max(8_000),
  tokenEstimate: z.number().int().nonnegative(),
  embedding: z.array(z.number()).length(LIMITS.embeddingDims).nullable(),
});
export type DocumentChunk = z.infer<typeof DocumentChunkSchema>;

export const PiiCategorySchema = z.enum([
  "name",
  "email",
  "phone",
  "address",
  "idNumber",
  "bankDetail",
  "card",
]);
export type PiiCategory = z.infer<typeof PiiCategorySchema>;

export type PiiReport = {
  counts: Record<PiiCategory, number>;
  total: number;
  samples: { category: PiiCategory; token: string }[];
};

/** The document as the browser holds it. Nothing is persisted server-side. */
export const DocumentPayloadSchema = z.object({
  documentId: z.string().regex(/^doc_[a-f0-9]{16,64}$/),
  name: z.string().min(1).max(200),
  pages: z.array(PageSchema).min(1).max(LIMITS.maxPages),
});
export type DocumentPayload = z.infer<typeof DocumentPayloadSchema>;

export const RetrievalModeSchema = z.enum(["hybrid", "lexical"]);
export type RetrievalMode = z.infer<typeof RetrievalModeSchema>;

export type IngestedDocument = DocumentPayload & {
  chunks: DocumentChunk[];
  retrievalMode: RetrievalMode;
  source: "pdf" | "text" | "ocr";
  pii: PiiReport | null;
  injectionsNeutralized: number;
  /** Object URL of the original PDF, browser only. */
  fileUrl: string | null;
};

// ---------------------------------------------------------------------------
// Citations
// ---------------------------------------------------------------------------

export const CitationSchema = z.object({
  page: z.number().int().min(1).describe("Page number from the page attribute of the context block"),
  clause: z.string().describe("Clause heading or number, e.g. '7. Non-Competition'"),
  excerpt: z
    .string()
    .describe("Verbatim quote of 5-30 words copied exactly from the context block"),
});
export type Citation = z.infer<typeof CitationSchema>;

export type VerifiedCitation = Citation & { verified: boolean };

// ---------------------------------------------------------------------------
// Module A: Summary
// ---------------------------------------------------------------------------

export const SummaryModelSchema = z.object({
  documentType: z.string().describe("e.g. 'Mutual NDA', 'Residential lease', 'Employment agreement'"),
  parties: z.array(z.string()).describe("Roles of the parties, e.g. 'Employer', 'Employee'"),
  tldr: z.string().describe("Plain-English summary, at most 3 sentences, grade-8 reading level"),
  keyObligations: z.array(z.string()).describe("What the reader must do, one plain sentence each"),
  keyRights: z.array(z.string()).describe("What the reader is entitled to, one plain sentence each"),
  duration: z.string().nullable().describe("Term / length of the agreement, or null if not stated"),
  governingLaw: z.string().nullable().describe("Governing law / jurisdiction, or null if not stated"),
  keyDates: z
    .array(z.object({ label: z.string(), value: z.string() }))
    .describe("Deadlines, notice periods, renewal dates"),
  options: z
    .array(z.object({ option: z.string(), whatItMeans: z.string() }))
    .describe("2-4 realistic options open to the reader (e.g. sign as is, ask for a change, walk away) and what each means, informational only"),
  checklist: z.array(z.string()).describe("4-8 concrete checks to do before signing, each a short imperative sentence"),
  citations: z.array(CitationSchema),
});
export type SummaryModel = z.infer<typeof SummaryModelSchema>;

export const SummaryOutputSchema = SummaryModelSchema.extend({
  tldr: z.string().min(1),
  disclaimer: z.literal(DISCLAIMER),
});
export type SummaryOutput = z.infer<typeof SummaryOutputSchema>;

// ---------------------------------------------------------------------------
// Module B: Red flags
// ---------------------------------------------------------------------------

export const SeveritySchema = z.enum(["CRITICAL", "HIGH", "MEDIUM", "LOW"]);
export type Severity = z.infer<typeof SeveritySchema>;

export const SEVERITY_ORDER: Record<Severity, number> = {
  CRITICAL: 0,
  HIGH: 1,
  MEDIUM: 2,
  LOW: 3,
};

export const FlagTypeSchema = z.enum([
  "one_sided_indemnification",
  "auto_renewal",
  "non_compete",
  "mandatory_arbitration",
  "ip_assignment",
  "unilateral_amendment",
  "liability_cap",
  "liquidated_damages",
  "termination_for_convenience",
  "third_party_data_sharing",
  "other",
]);
export type FlagType = z.infer<typeof FlagTypeSchema>;

export const FLAG_LABELS: Record<FlagType, string> = {
  one_sided_indemnification: "One-sided indemnification",
  auto_renewal: "Auto-renewal",
  non_compete: "Non-compete",
  mandatory_arbitration: "Mandatory arbitration",
  ip_assignment: "IP ownership assignment",
  unilateral_amendment: "Unilateral amendment right",
  liability_cap: "Limitation of liability",
  liquidated_damages: "Liquidated damages",
  termination_for_convenience: "Termination for convenience",
  third_party_data_sharing: "Data sharing with third parties",
  other: "Other risk",
};

export const RedFlagSchema = z.object({
  severity: SeveritySchema,
  flagType: FlagTypeSchema,
  title: z.string().describe("Short name for this specific issue, sentence case"),
  plainExplanation: z.string().describe("What the clause means for the reader, plain English, 1-3 sentences"),
  recommendation: z.string().describe("What the reader could ask for or check, informational only"),
  citation: CitationSchema,
});
export type RedFlag = z.infer<typeof RedFlagSchema>;

export const RedFlagModelSchema = z.object({
  overallRiskScore: z
    .number()
    .min(0)
    .max(100)
    .describe("0 = very balanced, 100 = extremely one-sided against the reader"),
  overallAssessment: z.string().describe("One or two sentences on the overall balance of the document"),
  flags: z.array(RedFlagSchema),
});
export type RedFlagModel = z.infer<typeof RedFlagModelSchema>;

/** Spec shape: the red flag list itself. */
export const RedFlagOutputSchema = z.array(RedFlagSchema);
export type RedFlagOutput = z.infer<typeof RedFlagOutputSchema>;

export type HeuristicFlag = {
  flagType: Exclude<FlagType, "other">;
  severity: Severity;
  page: number;
  clause: string;
  excerpt: string;
  reason: string;
};

// ---------------------------------------------------------------------------
// Module C: Compare
// ---------------------------------------------------------------------------

export const DiffKindSchema = z.enum(["added", "removed", "modified", "unchanged"]);
export type DiffKind = z.infer<typeof DiffKindSchema>;

export type Clause = {
  id: string;
  heading: string;
  text: string;
  normalized: string;
  page: number;
};

export type DiffRow = {
  id: string;
  kind: DiffKind;
  heading: string;
  before: Clause | null;
  after: Clause | null;
  similarity: number;
  /** Word-level Myers diff for modified rows. */
  wordDiff: { op: "equal" | "insert" | "delete"; text: string }[] | null;
};

export const RiskDeltaSchema = z.enum(["MORE_RISK", "LESS_RISK", "NEUTRAL"]);
export type RiskDelta = z.infer<typeof RiskDeltaSchema>;

export const DiffAnnotationSchema = z.object({
  rowId: z.string().describe("The id attribute of the change block being annotated"),
  whatChanged: z.string().describe("Plain-English description of the change"),
  whyItMatters: z.string().describe("Practical consequence for the reader"),
  riskDelta: RiskDeltaSchema,
  severity: SeveritySchema,
});
export type DiffAnnotation = z.infer<typeof DiffAnnotationSchema>;

export const CompareModelSchema = z.object({
  verdict: z.string().describe("Two sentences: overall, is version B better or worse for the reader and why"),
  annotations: z.array(DiffAnnotationSchema),
});
export type CompareModel = z.infer<typeof CompareModelSchema>;

export type DiffOutput = {
  rows: DiffRow[];
  stats: Record<DiffKind, number>;
  verdict: string;
  annotations: DiffAnnotation[];
  disclaimer: typeof DISCLAIMER;
};

// ---------------------------------------------------------------------------
// Module D: Grounded Q&A
// ---------------------------------------------------------------------------

export const AnswerModelSchema = z.object({
  answerable: z
    .boolean()
    .describe("false if the context blocks do not contain the information needed"),
  answer: z.string().describe("Plain-English answer using only the context blocks"),
  citations: z.array(CitationSchema),
  confidence: z.enum(["high", "medium", "low"]),
  followUps: z.array(z.string()).describe("Up to 3 related questions the reader could ask next"),
});
export type AnswerModel = z.infer<typeof AnswerModelSchema>;

export const RetrievedChunkSchema = z.object({
  id: z.string(),
  page: z.number().int(),
  section: z.string(),
  preview: z.string(),
  vectorScore: z.number().nullable(),
  lexicalScore: z.number(),
  fusedScore: z.number(),
  rerankScore: z.number().nullable(),
});
export type RetrievedChunk = z.infer<typeof RetrievedChunkSchema>;

export const GroundedAnswerSchema = z.object({
  status: z.enum(["answered", "refused"]),
  answer: z.string(),
  refusalReason: z.string().nullable(),
  citations: z.array(CitationSchema.extend({ verified: z.boolean() })),
  confidence: z.enum(["high", "medium", "low"]),
  followUps: z.array(z.string()),
  faithfulness: z.object({
    verifiedCitations: z.number().int(),
    totalCitations: z.number().int(),
    passed: z.boolean(),
  }),
  retrieved: z.array(RetrievedChunkSchema),
  disclaimer: z.literal(QA_DISCLAIMER),
});
export type GroundedAnswer = z.infer<typeof GroundedAnswerSchema>;

/** NDJSON events streamed by /api/ask so the UI can show each RAG stage live. */
export type AskEvent =
  | { type: "stage"; stage: "retrieve" | "rerank" | "generate" | "verify"; detail: string }
  | { type: "retrieved"; chunks: RetrievedChunk[] }
  | { type: "result"; data: GroundedAnswer }
  | { type: "error"; error: string; code: string };

// ---------------------------------------------------------------------------
// Module E: Attorney consultation sheet
// ---------------------------------------------------------------------------

export const ConsultItemSchema = z.object({
  clauseTitle: z.string(),
  priority: SeveritySchema,
  whyAsk: z.string().describe("Why this clause is ambiguous or risky, plain English"),
  questions: z.array(z.string()).describe("2-4 specific questions to ask an attorney"),
  citation: CitationSchema,
});
export type ConsultItem = z.infer<typeof ConsultItemSchema>;

export const ConsultModelSchema = z.object({
  documentTitle: z.string(),
  situationSummary: z.string().describe("2-3 sentence neutral summary to read to the attorney"),
  items: z.array(ConsultItemSchema).describe("5 to 10 clauses, most important first"),
  documentsToBring: z.array(z.string()),
  generalQuestions: z.array(z.string()).describe("Questions not tied to one clause"),
});
export type ConsultModel = z.infer<typeof ConsultModelSchema>;

export const ConsultationSheetSchema = ConsultModelSchema.extend({
  items: z.array(ConsultItemSchema).min(1).max(10),
  disclaimer: z.literal(DISCLAIMER),
});
export type ConsultationSheet = z.infer<typeof ConsultationSheetSchema>;

// ---------------------------------------------------------------------------
// API request bodies
// ---------------------------------------------------------------------------

export const IngestRequestSchema = z.object({
  name: z.string().min(1).max(200),
  pages: z.array(PageSchema).min(1).max(LIMITS.maxPages),
  source: z.enum(["pdf", "text", "ocr"]),
});
export type IngestRequest = z.infer<typeof IngestRequestSchema>;

export type IngestResponse = {
  documentId: string;
  chunks: DocumentChunk[];
  retrievalMode: RetrievalMode;
  injectionsNeutralized: number;
  pages: Page[];
};

export type OcrResponse = {
  pages: Page[];
  method: "pdf-parse" | "gemini-ocr";
};

export const DocumentRequestSchema = z.object({
  documentId: z.string(),
  document: DocumentPayloadSchema,
  preferences: PreferencesSchema.optional(),
});

export const SummarizeRequestSchema = DocumentRequestSchema.extend({
  focus: z.string().max(LIMITS.maxQueryChars).optional(),
});

export const RedFlagsRequestSchema = DocumentRequestSchema.extend({
  perspective: z.string().max(80).optional(),
});

export const CompareRequestSchema = z.object({
  documentIdA: z.string(),
  documentIdB: z.string(),
  documentA: DocumentPayloadSchema,
  documentB: DocumentPayloadSchema,
  preferences: PreferencesSchema.optional(),
});

export const AskRequestSchema = DocumentRequestSchema.extend({
  query: z.string().trim().min(3, "Ask a longer question").max(LIMITS.maxQueryChars),
  chunks: z.array(DocumentChunkSchema).min(1).max(LIMITS.maxChunks),
});

export const ConsultRequestSchema = DocumentRequestSchema.extend({
  concerns: z.string().max(LIMITS.maxQueryChars).optional(),
});

export type ApiError = { error: string; code: string };
