"use client";

import * as React from "react";
import { Hero, SiteHeader } from "@/components/hero";
import { Workspace } from "@/components/workspace/workspace";
import { WorkspaceProvider, useWorkspace } from "@/components/workspace/workspace-context";
import { PreferencesProvider } from "@/components/preferences";
import { ingestPages, readableError } from "@/lib/api-client";
import { paginateText, scrubPII } from "@/lib/ingestion";
import { SAMPLE_REVISED_NDA } from "@/lib/samples";

export default function Home() {
  return (
    <PreferencesProvider>
      <WorkspaceProvider>
        <SiteHeader />
        <main>
          <HeroWithSample />
          <Workspace />
        </main>
        <footer className="mx-auto max-w-[1440px] px-4 py-8 text-xs text-ink-soft sm:px-6">
          <p className="max-w-3xl">
            Legal Information Navigator provides general legal information generated by Google Gemini. It is not a law firm and does not give legal advice;
            no attorney-client relationship is created. Documents are processed only for the duration of each request and are never stored.
          </p>
        </footer>
      </WorkspaceProvider>
    </PreferencesProvider>
  );
}

function HeroWithSample() {
  const { setDocument } = useWorkspace();
  const [error, setError] = React.useState<string | null>(null);

  const trySample = async () => {
    setError(null);
    document.getElementById("workspace")?.scrollIntoView({ behavior: "smooth" });
    try {
      const { pages, report } = scrubPII(paginateText(SAMPLE_REVISED_NDA));
      const res = await ingestPages("Client-revised NDA.txt", pages, "text");
      setDocument("primary", {
        documentId: res.documentId,
        name: "Client-revised NDA.txt",
        pages: res.pages,
        chunks: res.chunks,
        retrievalMode: res.retrievalMode,
        source: "text",
        pii: report,
        injectionsNeutralized: res.injectionsNeutralized,
        fileUrl: null,
      });
    } catch (err) {
      setError(readableError(err).message);
    }
  };

  return (
    <>
      <Hero onTrySample={() => void trySample()} />
      {error && (
        <p role="alert" className="mx-auto max-w-[1440px] px-6 pt-4 text-sm text-redline">
          {error}
        </p>
      )}
    </>
  );
}
