"use client";

import * as React from "react";
import { AlertTriangle, BookOpenCheck, CircleSlash, CircleStop, Quote, Scale, Sparkles } from "lucide-react";
import type { Citation, Severity } from "@/types/legal";
import { cn } from "@/lib/utils";
import { useWorkspace, type DocSlot } from "@/components/workspace/workspace-context";
import { Button } from "@/components/ui/button";

// ---------------------------------------------------------------------------

const SEVERITY_STYLE: Record<Severity, { cls: string; label: string }> = {
  CRITICAL: { cls: "bg-sev-critical-bg text-sev-critical-fg ring-sev-critical-fg/30", label: "Critical" },
  HIGH: { cls: "bg-sev-high-bg text-sev-high-fg ring-sev-high-fg/30", label: "High" },
  MEDIUM: { cls: "bg-sev-medium-bg text-sev-medium-fg ring-sev-medium-fg/30", label: "Medium" },
  LOW: { cls: "bg-sev-low-bg text-sev-low-fg ring-sev-low-fg/30", label: "Low" },
};

const SEVERITY_SHAPE: Record<Severity, string> = {
  CRITICAL: "M6 1 11 11H1z",
  HIGH: "M6 1 11 6 6 11 1 6z",
  MEDIUM: "M2 2h8v8H2z",
  LOW: "M6 2a4 4 0 1 1 0 8 4 4 0 0 1 0-8z",
};

/** Colour plus a distinct shape, so severity never depends on colour alone. */
export function SeverityBadge({ severity, className }: { severity: Severity | undefined; className?: string }) {
  if (!severity) return null;
  const s = SEVERITY_STYLE[severity];
  return (
    <span className={cn("inline-flex items-center gap-1.5 rounded-pill px-2 py-0.5 text-2xs font-bold ring-1 ring-inset", s.cls, className)}>
      <svg viewBox="0 0 12 12" className="size-2.5 fill-current" aria-hidden>
        <path d={SEVERITY_SHAPE[severity]} />
      </svg>
      {s.label}
      <span className="sr-only"> severity</span>
    </span>
  );
}

// ---------------------------------------------------------------------------

export function CitationLink({
  citation,
  slot = "primary",
  verified,
  compact = false,
}: {
  citation: Partial<Citation> | undefined;
  slot?: DocSlot;
  verified?: boolean;
  compact?: boolean;
}) {
  const { focusCitation } = useWorkspace();
  if (!citation?.page || !citation.excerpt) return null;
  const { page, excerpt, clause } = citation;
  return (
    <button
      type="button"
      onClick={() => focusCitation({ page, excerpt }, slot)}
      className={cn(
        "group block w-full rounded-control border-l-2 border-highlight bg-highlight/10 text-left transition-colors hover:bg-highlight/25",
        compact ? "px-2.5 py-1.5" : "px-3 py-2",
      )}
      aria-label={`Show page ${page}${clause ? `, ${clause}` : ""} in the document`}
    >
      <span className="flex items-center gap-2 text-2xs font-semibold text-ink-soft">
        <Quote className="size-3" aria-hidden />
        <span>
          Page {page}
          {clause ? `, ${clause}` : ""}
        </span>
        {verified === true && (
          <span className="ml-auto inline-flex items-center gap-1 text-seal" title="Quote found in your document">
            <BookOpenCheck className="size-3" aria-hidden /> Verified quote
          </span>
        )}
        {verified === false && (
          <span className="ml-auto inline-flex items-center gap-1 text-amber" title="Could not match this quote exactly">
            <AlertTriangle className="size-3" aria-hidden /> Unverified
          </span>
        )}
      </span>
      {!compact && <span className="mt-1 block font-serif text-sm italic leading-snug text-ink/85 line-clamp-3">&ldquo;{excerpt}&rdquo;</span>}
    </button>
  );
}

// ---------------------------------------------------------------------------

export function Disclaimer({ text }: { text: string }) {
  return (
    <div role="note" className="flex items-start gap-2.5 border-t border-rule bg-paper/95 px-4 py-3 text-xs text-ink-soft backdrop-blur">
      <Scale className="mt-0.5 size-4 shrink-0" aria-hidden />
      <p>{text}</p>
    </div>
  );
}

// ---------------------------------------------------------------------------

/** Marks exactly where Gemini is working, and which model answered. */
export function GenAiStatus({
  state,
  model,
  label,
  onStop,
}: {
  state: "idle" | "streaming" | "done" | "error";
  model?: string | null;
  label: string;
  onStop?: () => void;
}) {
  return (
    <div className="flex flex-wrap items-center gap-2 text-xs" aria-live="polite">
      <span
        className={cn(
          "inline-flex items-center gap-1.5 rounded-pill px-2.5 py-1 font-semibold",
          state === "streaming" ? "bg-highlight text-highlight-ink" : "bg-ink/5 text-ink-soft",
        )}
      >
        <Sparkles className={cn("size-3.5", state === "streaming" && "animate-pulse-soft")} aria-hidden />
        {state === "streaming" ? `Gemini is ${label}` : state === "done" ? "Generated by Gemini" : "Gemini"}
      </span>
      {model && <span className="text-ink-soft">{model}</span>}
      {state === "streaming" && onStop && (
        <Button variant="ghost" size="sm" onClick={onStop} className="ml-auto">
          <CircleStop aria-hidden /> Stop
        </Button>
      )}
    </div>
  );
}

export function StreamingCaret({ show }: { show: boolean }) {
  if (!show) return null;
  return <span className="ml-0.5 inline-block h-[1.05em] w-[2px] translate-y-[2px] animate-caret-blink bg-ink align-baseline" aria-hidden />;
}

export function ErrorNotice({ message, onRetry }: { message: string; onRetry?: () => void }) {
  return (
    <div role="alert" className="flex items-start gap-3 rounded-control border border-redline/30 bg-redline/5 p-3 text-sm">
      <CircleSlash className="mt-0.5 size-4 shrink-0 text-redline" aria-hidden />
      <p className="flex-1 text-ink">{message}</p>
      {onRetry && (
        <Button variant="secondary" size="sm" onClick={onRetry}>
          Try again
        </Button>
      )}
    </div>
  );
}

export function SectionHeading({ children, count }: { children: React.ReactNode; count?: number }) {
  return (
    <h3 className="mb-2 flex items-baseline gap-2 font-sans text-sm font-bold text-ink">
      {children}
      {count !== undefined && <span className="font-normal text-ink-soft">{count}</span>}
    </h3>
  );
}

export function SkeletonLines({ lines = 3 }: { lines?: number }) {
  return (
    <div className="space-y-2" aria-hidden>
      {Array.from({ length: lines }, (_, i) => (
        <div key={i} className="h-3 animate-pulse-soft rounded-sheet bg-ink/10" style={{ width: `${92 - i * 14}%` }} />
      ))}
    </div>
  );
}

/** Renders scrubbed text with PII placeholders styled as tokens. */
export function WithPiiTokens({ text }: { text: string }) {
  const parts = text.split(/(\[(?:NAME|EMAIL|PHONE|ADDRESS|ID|BANK|CARD)_\d+\])/g);
  return (
    <>
      {parts.map((p, i) =>
        /^\[(?:NAME|EMAIL|PHONE|ADDRESS|ID|BANK|CARD)_\d+\]$/.test(p) ? (
          <span key={i} className="pii-token" title="Personal detail removed before analysis">
            {p.slice(1, -1).replace("_", " ").toLowerCase()}
          </span>
        ) : (
          <React.Fragment key={i}>{p}</React.Fragment>
        ),
      )}
    </>
  );
}
